### ISSUE TITLE
Website Docs

### ISSUE THREAD

**Issue by RONNOC777** [PoweredRails/PoweredRails#1]
The documents for the API should be uploaded onto the Website in the developer platform.

It should be easy to find what you want and show a detailed description for each method.

**Comment by Phasesaber** [comment]
JavaDocs!

**Comment by RONNOC777** [comment]
Yep xP

**Comment by JamenMarz** [comment]
Closed, see #2, adding a TODO list with everything we need to do.

**Comment by Phasesaber** [comment]
Nice job closing @JamenMarz :3

**Comment by JamenMarz** [comment]
Lel, I don't have permission to add/remove labels either, something is wrong.

**Comment by Phasesaber** [comment]
@JamenMarz It's because you're not a collaborator on the repo, ask @RONNOC777 to add you.

**Comment by RONNOC777** [comment]
@JamenMarz, fixed permission.
